name: Testing for first time
on: 
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the code
        uses: actions/checkout@v3  
      - name: donwload the node js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci


    Deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: checkout the code
        uses: actions/checkout@v3  
      - name: donwload the node js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Deployment
        run: echo "Deployement is succesffuly completed"
          
